version: '3.8'

services:
  mqtt-client:
    build:
      context: ./docker/mqtt-client
      dockerfile: Dockerfile
    container_name: mqtt-client
    restart: always
    depends_on:
      - database
    environment:
      MYSQL_USER: root

  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

