global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9091"]
  - job_name: mqtt
    static_configs:
      - targets: ["mosquitto_exporter:9234"]
