---
- name: Deploy MQTT Docker Services
  hosts: vm
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Ensure any held packages are released
      command: apt-mark unhold containerd
      ignore_errors: yes

    - name: Remove conflicting containerd if installed
      apt:
        name: containerd
        state: absent
      ignore_errors: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker’s official APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"  
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Create project directory on the remote server
      file:
        path: "/home/{{ ansible_user }}/ResearchProject"
        state: directory
        mode: '0755'

    - name: Create docker directory on the remote server
      file:
        path: "/home/{{ ansible_user }}/ResearchProject/docker"
        state: directory
        mode: '0755'

    - name: Create mqtt-client directory on the remote server
      file:
        path: "/home/{{ ansible_user }}/ResearchProject/docker/mqtt-client"
        state: directory
        mode: '0755'
    
    - name: Create volumes directory on the remote server
      file:
        path: "/home/{{ ansible_user }}/ResearchProject/volumes"
        state: directory
        mode: '0755'

    - name: Copy MQTT Client Dockerfile to the remote server
      copy:
        src: "/home/labdoo/Desktop/Briti Laptop Data/University/ResearchProject/docker/mqtt-client/Dockerfile"
        dest: "/home/{{ ansible_user }}/ResearchProject/docker/mqtt-client/Dockerfile"

    - name: Copy Docker Compose file to the remote server
      copy:
        src: "/home/labdoo/Desktop/Briti Laptop Data/University/ResearchProject/docker-compose.yml"
        dest: "/home/{{ ansible_user }}/ResearchProject/docker-compose.yml"

    - name: Copy MQTT Client files to the remote server
      copy:
        src: "/home/labdoo/Desktop/Briti Laptop Data/University/ResearchProject/docker/mqtt-client/"
        dest: "/home/{{ ansible_user }}/ResearchProject/docker/mqtt-client/"
        mode: '0755'
    
    - name: Copy MQTT config file to the remote server
      copy:
        src: "/home/labdoo/Desktop/Briti Laptop Data/University/ResearchProject/volumes/mosquitto.conf"
        dest: "/home/{{ ansible_user }}/ResearchProject/volumes/"
  
    - name: Build and start the application using Docker Compose
      command: docker-compose up -d
      args:
        chdir: "/home/{{ ansible_user }}/ResearchProject/docker/mqtt-client/"
